apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: deepakagrawalmsoe-dev
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          # Reference the ImageStream tag created by your binary build.
          # OpenShift will update this ImageStream tag when a new build is triggered.
          image: flask-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http      # For application traffic.
            - containerPort: 8080
              name: metrics   # For Prometheus to scrape /metrics.
