apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: deepakagrawalmsoe-dev
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          # Reference the ImageStream tag created by your binary build.
          # OpenShift will update this ImageStream tag when a new build is triggered.
          image: flask-app:latest
          #image: image-registry.openshift-image-registry.svc:5000/deepakagrawalmsoe-dev/flask-app@sha256:8d0f7bcd01a36d2f12c232a15ae3aa7e0f405487d362b771abf4acb0852bbe59
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http      # For application traffic.
            - containerPort: 8080
              name: metrics   # For Prometheus to scrape /metrics.
