apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: deepakagrawalmsoe-dev
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8080
      targetPort: 8080
